# Generated by Django 4.0.2 on 2022-02-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
